#!/usr/bin/env bash
# Configures a new Ubuntu machine by installing Nginx and configuring redirection

# Update package lists and install Nginx
echo "Updating and installing Nginx..."
sudo apt-get update -y -qq && sudo apt-get install nginx -y

# Start Nginx service
sudo service nginx start

# Allow SSH connections to avoid being locked out
sudo ufw allow OpenSSH

# Allow Nginx on firewall
sudo ufw allow 'Nginx HTTP'

# Give the user ownership to website files for easy editing
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www

# Backup default index
sudo cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp

# Create a new index with "Hello World!"
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html >/dev/null

# Restart Nginx
sudo service nginx restart

echo "Redirection configuration completed."
