#!/usr/bin/env bash
# Install nginx web server

apt-get update
apt-get install -y nginx

cat > /var/www/html/index.html <<EOF
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Hello World!></title>
    </head>
    <body>
        <h1>Hello World!</h1>
    </body>
</html> 
EOF

cat > /etc/nginx/sites-available/default <<EOF
server {
    listen 80 default_server;
    listen [::]:80 default_server;
    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;
    server_name _;
    location / {
        try_files \$uri \$uri/ =404;
    }
}
EOF

service nginx restart > /dev/null 2>&1