#!/usr/bin/env bash
# Configures a new Ubuntu machine by installing Nginx
# and setting up a redirection to return a 301 status code

# Update and install Nginx
sudo apt-get update -y -qq && sudo apt-get install nginx -y

# Start Nginx service
sudo service nginx start

# Allow SSH connections to avoid being locked out
sudo ufw allow OpenSSH

# Allow Nginx HTTP traffic
sudo ufw allow 'Nginx HTTP'

# Give ownership of website files to the user
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www

# Backup default index
sudo cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp

# Create a new index with "Hello World!"
echo -e "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html >/dev/null

# Configure redirection in Nginx to return a 301 status code
sudo sed -i '/location \/ {/a \ \ \ \ \ \ \ \ rewrite ^/redirect_me https://www.example.com/ permanent;' /etc/nginx/sites-available/default

# Restart Nginx
sudo service nginx restart

echo -e "\nConfiguration complete.\n"
