#!/usr/bin/env bash
# a Bash script that displays To infinity and beyond indefinitely
# In between each iteration of the loop, there's a sleep 2

phrase="To infinity and beyond"
while true; do
	echo "$phrase"
	sleep 2
done
