#!/usr/bin/env bash
# a Bash script that stops 4-to_infinity_and_beyond process
pid=$(pgrep -f "4-to_infinity_and_beyond")
while [ -n "$pid" ]; do
    pkill "$pid"
    sleep 1
    pid=$(pgrep -f "4-to_infinity_and_beyond")
done
