#!/usr/bin/env bash
# Write a Bash script that displays:
# To infinity and beyond indefinitely
# With a sleep 2 in between each iteration
# I am invincible!!! when receiving a SIGTERM signal
phrase1="To infinity and beyond"                                                                            phrase2="I am invincible!!!"
while true; do
	echo "$phrase1"
	sleep 2
	trap 'echo "$phrase2"' SIGTERM
done
