#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
#+ but for 9th iteration, displays Best School 
#+ and then Hi on a new line.
phrase="Best School"
times=10
while [ $times -gt 0 ]; do
       	echo "$phrase"

	if [ $times -eq 2 ]; then
                echo "Hi"
	fi

        ((times--))
done
