#!/usr/bin/env bash
# a Bash script that loops from 1 to 10 and
#+ displays bad luck for the 4th loop iteration
#+ displays good luck for the 8th loop iteration
#+ displays Best School for the other iterations 
phrase="Best School"
times=10
while [ $times -gt 0 ]; do
       	if [ $times -eq 7 ]; then
                echo "bad luck"
	elif [ $times -eq 3 ]; then
		echo "good luck"
	else
		echo "$phrase"
	fi

        ((times--))
done
