#!/bin/bash

#Update and install ufw
echo -e "Installing ufw...\n"
sudo apt-get update
sudo apt-get install -y ufw

#deny incoming and allow outgoing traffic
sudo ufw default deny incoming
sudo ufw default allow outgoing

#Allow specif udp ports
sudo ufw allow 22/udp  #SSH
sudo ufw allow 80/udp  #HTTP
sudo ufw allow 443/udp  #HTTPS/SSL

#enable firewall
sudo ufw enable

echo -e "ufw configured.\n"
