#!/usr/bin/env bash
# a script that configures nginx.config file so that Nginx is running as the nginx user

# Update Nginx configuration to run as nginx user
sed -i 's/^user .*/user nginx;/' /etc/nginx/nginx.conf

# Update Nginx configuration to listen on port 8080 for all active IPs
sed -i 's/^listen 80;/listen 8080;/g' /etc/nginx/sites-available/default

# Restart Nginx service
systemctl restart nginx
